name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BRANCH: ${{ github.ref }}
      COMMIT: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v1
    - name: Run NPM install
      run: npm install
    - name: Run NPM test
      run:  npm test
    - name: Run NPM build
      run: npm run build
    - name: Create container image
      run: docker build -t xebxke/doudou:${BRANCH#refs/heads/}-${COMMIT} .
    - name: Log into Docker Hub
      run: docker login -u xebxke -p ${secret.EDOUARD_DOCKER_PASSWORD}
    - name: Push container image
      run: docker push xebxke/doudou:${BRANCH#refs/heads/}-${COMMIT}
