name: CI-franck-cussac

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BRANCH: ${{ github.ref }}
      COMMIT: ${{ github.sha }}

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and run
      run: |
        npm install
        npm test
        npm run build
    - name: build image docker
      run: |
      docker build -t xebxke/cactus:${BRANCH#refs/heads/}-$COMMIT .
      echo "::set-output name=docker_tag::xebxke/cactus:${BRANCH#refs/heads/}-$COMMIT"

    - name: Log in to docker registry
      env:
        DOCKER_REGISTRY: 'docker.io'
      run: echo ${{ secrets.SOLUTIONS_DOCKERHUB_PASSWORD }} | docker login $DOCKER_REGISTRY --username ${{ secrets.SOLUTIONS_DOCKERHUB_USERNAME }} --password-stdin

    - name: Publish docker image
      run: docker push xebxke/cactus:${BRANCH#refs/heads/}-$COMMIT

    - name: Notify Slack on success
      if: success()
      uses: ./.github/actions/slack-notifier
      env:
        SLACK_CHANNEL: "#xke-github-actions"
        SLACK_BOT: "githubActionRulz"
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      with:
        message: "${{ github.actor }} published a new image : ${{ steps.docker_build.outputs.docker_tag }}"
