name: CI-franck-cussac

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and run
      run: |
        npm install
        npm test
        npm run build


  docker:

    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
      COMMIT: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v1
      - name: build image docker
        run: |
          echo $GITHUB_SHA
          docker build -t xbexke/cactus/${BRANCH#/ref/head/}/$COMMIT .
